-- MySQL Script generated by MySQL Workbench
-- Wed Jun 22 14:59:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hashproject
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hashproject` ;

-- -----------------------------------------------------
-- Schema hashproject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hashproject` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `hashproject` ;

-- -----------------------------------------------------
-- Table `hashproject`.`hash_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hashproject`.`hash_table` ;

CREATE TABLE IF NOT EXISTS `hashproject`.`hash_table` (
  `hash_id` INT NOT NULL,
  `md5_hash` VARCHAR(16) NULL,
  `sha1_hash` VARCHAR(20) NULL,
  `sha256_hash` VARCHAR(32) NULL,
  `ssdeep_hash` VARCHAR(40) NULL,
  PRIMARY KEY (`hash_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hashproject`.`md5_hashes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hashproject`.`md5_hashes` ;

CREATE TABLE IF NOT EXISTS `hashproject`.`md5_hashes` (
  `idmd5` VARCHAR(16) NOT NULL,
  `hash_table_hash_id` INT NOT NULL,
  PRIMARY KEY (`idmd5`, `hash_table_hash_id`),
  CONSTRAINT `fk_md5_hashes_hash_table1`
    FOREIGN KEY (`hash_table_hash_id`)
    REFERENCES `hashproject`.`hash_table` (`hash_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_md5_hashes_hash_table1_idx` ON `hashproject`.`md5_hashes` (`hash_table_hash_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `hashproject`.`sha1_hashes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hashproject`.`sha1_hashes` ;

CREATE TABLE IF NOT EXISTS `hashproject`.`sha1_hashes` (
  `idsha1` VARCHAR(20) NOT NULL,
  `hash_table_hash_id` INT NOT NULL,
  PRIMARY KEY (`idsha1`, `hash_table_hash_id`),
  CONSTRAINT `fk_sha1_hashes_hash_table1`
    FOREIGN KEY (`hash_table_hash_id`)
    REFERENCES `hashproject`.`hash_table` (`hash_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_sha1_hashes_hash_table1_idx` ON `hashproject`.`sha1_hashes` (`hash_table_hash_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `hashproject`.`sha256_hashes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hashproject`.`sha256_hashes` ;

CREATE TABLE IF NOT EXISTS `hashproject`.`sha256_hashes` (
  `idsha256` VARCHAR(32) NOT NULL,
  `hash_table_hash_id` INT NOT NULL,
  PRIMARY KEY (`idsha256`, `hash_table_hash_id`),
  CONSTRAINT `fk_sha256_hashes_hash_table1`
    FOREIGN KEY (`hash_table_hash_id`)
    REFERENCES `hashproject`.`hash_table` (`hash_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_sha256_hashes_hash_table1_idx` ON `hashproject`.`sha256_hashes` (`hash_table_hash_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `hashproject`.`ssdeep_chunk_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hashproject`.`ssdeep_chunk_table` ;

CREATE TABLE IF NOT EXISTS `hashproject`.`ssdeep_chunk_table` (
  `chunk_id` INT NOT NULL,
  `chunk_size` INT NOT NULL,
  `chunk` INT NOT NULL,
  `hash_table_hash_id` INT NOT NULL,
  PRIMARY KEY (`chunk_id`),
  CONSTRAINT `fk_chunks_ssdeep_hashes`
    FOREIGN KEY (`hash_table_hash_id`)
    REFERENCES `hashproject`.`hash_table` (`hash_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_chunks_ssdeep_hashes_idx` ON `hashproject`.`ssdeep_chunk_table` (`hash_table_hash_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `hashproject`.`ssdeep_hashes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hashproject`.`ssdeep_hashes` ;

CREATE TABLE IF NOT EXISTS `hashproject`.`ssdeep_hashes` (
  `idssdeep` VARCHAR(40) NOT NULL,
  `hash_table_hash_id` INT NOT NULL,
  PRIMARY KEY (`idssdeep`, `hash_table_hash_id`),
  CONSTRAINT `fk_ssdeep_hashes_hash_table1`
    FOREIGN KEY (`hash_table_hash_id`)
    REFERENCES `hashproject`.`hash_table` (`hash_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ssdeep_hashes_hash_table1_idx` ON `hashproject`.`ssdeep_hashes` (`hash_table_hash_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
