-- MySQL Script generated by MySQL Workbench
-- Wed Jun 22 14:29:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hashproject
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hashproject` ;

-- -----------------------------------------------------
-- Schema hashproject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hashproject` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `hashproject` ;

-- -----------------------------------------------------
-- Table `hashproject`.`hash_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hashproject`.`hash_table` ;

CREATE TABLE IF NOT EXISTS `hashproject`.`hash_table` (
  `hash_id` INT NOT NULL,
  `ssdeep_hash` VARCHAR(40) NOT NULL,
  `md5_hash` VARCHAR(16) NULL,
  `sha1_hash` VARCHAR(20) NULL,
  `sha256_hash` VARCHAR(32) NULL,
  PRIMARY KEY (`hash_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hashproject`.`ssdeep_chunk_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hashproject`.`ssdeep_chunk_table` ;

CREATE TABLE IF NOT EXISTS `hashproject`.`ssdeep_chunk_table` (
  `chunk_id` INT NOT NULL,
  `chunk_size` INT NOT NULL,
  `chunk` INT NOT NULL,
  `ssdeep_hashes_hash_id` INT NOT NULL,
  PRIMARY KEY (`chunk_id`),
  CONSTRAINT `fk_chunks_ssdeep_hashes`
    FOREIGN KEY (`ssdeep_hashes_hash_id`)
    REFERENCES `hashproject`.`hash_table` (`hash_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_chunks_ssdeep_hashes_idx` ON `hashproject`.`ssdeep_chunk_table` (`ssdeep_hashes_hash_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
